services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
      - "24678:24678"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_STRAPI_API_URL=http://localhost:1337
    command: ["npm", "run", "dev", "--", "--host"]
