- name: Create User
  ansible.builtin.user:
    name: deploy
    shell: /bin/bash
    groups: sudo
    create_home: true

- name: Copy SSH Key
  ansible.builtin.authorized_key:
    user: deploy
    key: "{{ lookup('env', 'SSH_PUB_KEY') }}"
    state: present

- name: Allow sudo without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/deploy
    content: "deploy ALL=(ALL) NOPASSWD:ALL"
    mode: "0440"
