- name: Create directory
  ansible.builtin.file:
    path: /opt/tolkportal
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal

- name: Create docker compose file
  vars:
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
    node_env: "{{ lookup('env', 'NODE_ENV') }}"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/tolkportal/docker-compose.yml
    mode: "0700"
    owner: "tolkportal"
    group: "tolkportal"

- name: Create directory
  ansible.builtin.file:
    path: /opt/tolkportal/nginx
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal

- name: Create directory
  ansible.builtin.file:
    path: /opt/tolkportal/nginx/custom
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal

- name: Create directory
  ansible.builtin.file:
    path: /opt/tolkportal/nginx/custom/vhost.d
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal

- name: Copy using inline content
  ansible.builtin.copy:
    content: "client_max_body_size 20M;"
    dest: /opt/tolkportal/nginx/custom/vhost.d/api.myapp.org
    owner: tolkportal
    group: tolkportal
    mode: "0700"
