- name: Create directory
  ansible.builtin.file:
    path: /opt/tolkportal
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal

- name: Create docker compose file
  vars:
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
    node_env: "{{ lookup('env', 'NODE_ENV') }}"
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
    subdomain_name: "{{ lookup('env', 'SUBDOMAIN_NAME') }}"
    api_subdomain_name: "{{ lookup('env', 'API_SUBDOMAIN_NAME') }}"
    letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"
    app_keys: "{{ lookup('env', 'APP_KEYS') }}"
    api_token_salt: "{{ lookup('env', 'API_TOKEN_SALT') }}"
    admin_jwt_secret: "{{ lookup('env', 'ADMIN_JWT_SECRET') }}"
    transfer_token_salt: "{{ lookup('env', 'TRANSFER_TOKEN_SALT') }}"
    jwt_secret: "{{ lookup('env', 'JWT_SECRET') }}"
    aws_backup_bucket: "{{ lookup('env', 'AWS_BACKUP_BUCKET') }}"
    aws_access_key_backup: "{{ lookup('env', 'AWS_ACCESS_KEY_BACKUP') }}"
    aws_secret_key_backup: "{{ lookup('env', 'AWS_SECRET_KEY_BACKUP') }}"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/tolkportal/docker-compose.yml
    mode: "0700"
    owner: "tolkportal"
    group: "tolkportal"

- name: Create nginx config directory
  ansible.builtin.file:
    path: /opt/tolkportal/nginx/vhost.d
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal
    recurse: true

- name: Create backend media directory
  ansible.builtin.file:
    path: /opt/tolkportal/data/uploads
    state: directory
    mode: "0700"
    owner: tolkportal
    group: tolkportal
    recurse: true

- name: Create nginx config
  vars:
    domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
    subdomain_name: "{{ lookup('env', 'SUBDOMAIN_NAME') }}"
    api_subdomain_name: "{{ lookup('env', 'API_SUBDOMAIN_NAME') }}"
  ansible.builtin.copy:
    content: "client_max_body_size 20M;"
    dest: /opt/tolkportal/nginx/vhost.d/{{ api_subdomain_name ~ "." ~ domain_name }}
    owner: tolkportal
    group: tolkportal
    mode: "0700"
