- name: Diasble SSH for root
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart SSH

- name: Disable password login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  notify: Restart SSH

# - name: Install Fail2Ban
#   ansible.builtin.apt:
#     name: fail2ban
#     state: present
#
# - name: Create Fail2Ban filter for root
#   ansible.builtin.template:
#     src: ssh-root.conf.j2
#     dest: /etc/fail2ban/filter.d/sshd-root.conf
#     mode: '0644'
#     owner: root
#     group: root
#   notify: Restart Fail2Ban
#
# - name: Copy Fail2Ban config
#   ansible.builtin.template:
#     src: jail.local.j2
#     dest: /etc/fail2ban/jail.local
#     mode: '0644'
#     owner: root
#     group: root
#   notify: Restart Fail2Ban

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Turn-on auto update
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    create: true
    line: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - 'APT::Periodic::Update-Package-Lists "1";'
    - 'APT::Periodic::Unattended-Upgrade "1";'

- name: Setup UFW
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
    policy: deny
