name: Deploy Test

on:
  push:
    branches:
      - test

jobs:
  build-and-push:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:test .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tolkportal_backend:test
        working-directory: backend

      - name: Build and push Frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:test .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tolkportal_frontend:test
        working-directory: frontend
